title: Disorganized Thoughts
baseUrl: http://jshtab.github.io/
copyright: Copyright 2023, Jacob Shtabnoy
defaultContentLanguage: en

params:
  description: An unordered bin containing questions, half-baked ideas and the disorganized thoughts of a young software developer.


menu:
  socials:
  - url: https://github.com/jshtab
    name: GitHub
    params:
      icon: fa-svg/brands/github.svg
    weight: 1
  - url: '/contact'
    name: E-Mail
    params:
      icon: fa-svg/solid/envelope.svg
    weight: 2
  - url: https://www.linkedin.com/in/jacob-shtabnoy-a9077624b
    name: LinkedIn
    weight: 3
    params:
      icon: fa-svg/brands/linkedin.svg
