title: Jacob Shtabnoy
baseUrl: https://jshtab.github.io/
copyright: 2023, 2025 Jacob Shtabnoy
defaultContentLanguage: en

params:
  description: Personal blog of Jacob Shtabnoy.

markup:
  highlight:
    style: witchhazel
  goldmark:
    renderer:
      unsafe: true
    extensions:
      extras:
        superscript:
          enable: true

menu:
  socials:
  - url: https://github.com/jshtab
    name: GitHub
    params:
      icon: fa-svg/brands/github.svg
    weight: 1
  - url: '/contact'
    name: E-Mail
    params:
      icon: fa-svg/solid/envelope.svg
    weight: 2
  - url: https://www.linkedin.com/in/jshtab
    name: LinkedIn
    weight: 3
    params:
      icon: fa-svg/brands/linkedin.svg
  main:
  - url: '/guide'
    name: Guides
  # - url: '/project'
  #   name: Projects
  - url: '/blog'
    name: Blog
